### ISSUE TITLE
Error submitting code

### ISSUE THREAD

**Issue by hkup859** [sigmaSd/Aoc2024Bench#1]
I'm trying to submit my code to compare against the other solutions, but I'm getting the following error:
"Error submitting solution: Execution error: Expected 1579939 but got NaN"

The code follows the format best I can tell, it has a solution function taking in an input, I define a function to process that input, then return the answer from the solution function. It works locally when I run it with deno and outputs the correct result, so I'm not sure if I'm misunderstanding the submission criteria or if something is broken. Happy to share my code if you'd like.

**Comment by sigmaSd** [comment]
That seems like your code is not working correctly against the input, did you try locally against the input with the solution function the input you can find it under puzzles directory in this repo

**Comment by sigmaSd** [comment]
If you did then please share the code and I ca debug it

**Comment by hkup859** [comment]
I tried it against the Advent of Code input. I will pull your input from this repo and try that to see if there is a difference in the 2 causing an issue.

**Comment by hkup859** [comment]
I verified it is working when I use your input as well and gives the correct answer.

Here is the code I'm attempting to submit:
```
const formatInput = (input) => {
    const halfSplitList = input.split('\n')
    const list1 = []
    const list2 = []
    for (let i = 0; i < halfSplitList.length; i++) {
        const fullSplit = halfSplitList[i].split('   ')
        list1.push(fullSplit[0])
        list2.push(fullSplit[1])
    }
    
    const sortedList1 = list1.sort();
    const sortedList2 = list2.sort();

    return {sortedList1, sortedList2}
}


function solution(input) {
    let totalDifference = 0;
    const {sortedList1, sortedList2} = formatInput(input)
    for (let i = 0; i < sortedList1.length; i++) {
      totalDifference += Math.abs(sortedList1[i] - sortedList2[i]);
    }
    return totalDifference
}
```

The only difference when testing locally is I'm adding the input to a variable and calling the solution function so I can print the results.

**Comment by sigmaSd** [comment]
I get the same error locally
![image](https://github.com/user-attachments/assets/b69d29c8-70c8-4ed1-886f-0566c208aecf)

**Comment by sigmaSd** [comment]
you seem to be missing string -> number conversion

**Comment by sigmaSd** [comment]
Here is claude review

```
this code gives NAN any idea why

Looking at your code and the input file, there are a few issues that are causing the NaN result:

1. Your input file contains strings, but you're trying to perform numerical operations on them directly.
2. Some entries in your input file appear to be numbers in string format, but you're not converting them to numbers before subtraction.

Here's the corrected version of your code:

```typescript
const input = await fetch(import.meta.resolve("./puzzles/day1.txt")).then((r) =>
  r.text()
);

const formatInput = (input: string) => {
  const halfSplitList = input.split("\n");
  const list1: number[] = [];
  const list2: number[] = [];
  
  for (let i = 0; i < halfSplitList.length; i++) {
    const fullSplit = halfSplitList[i].split(/\s+/); // Use regex to split on any number of whitespace
    if (fullSplit.length >= 2) {
      list1.push(parseInt(fullSplit[0]));
      list2.push(parseInt(fullSplit[1]));
    }
  }

  const sortedList1 = list1.sort((a, b) => a - b);
  const sortedList2 = list2.sort((a, b) => a - b);

  return { sortedList1, sortedList2 };
};

function solution(input: string) {
  let totalDifference = 0;
  const { sortedList1, sortedList2 } = formatInput(input);
  
  for (let i = 0; i < sortedList1.length; i++) {
    if (!isNaN(sortedList1[i]) && !isNaN(sortedList2[i])) {
      totalDifference += Math.abs(sortedList1[i] - sortedList2[i]);
    }
  }
  return totalDifference;
}

console.log(solution(input));
```

Key changes made:

1. Changed the string splitting to use regex `/\s+/` to handle multiple spaces
2. Added type annotations to make the code more type-safe
3. Converting string values to numbers using `parseInt()`
4. Added proper numeric sorting with `(a, b) => a - b`
5. Added a check for `isNaN()` before performing calculations

The main reason you were getting NaN was because you were trying to perform mathematical operations on strings without converting them to numbers first. When you try to subtract strings, JavaScript attempts to convert them to numbers, but if it fails, you get NaN.

Also, your input file seems to have numbers separated by multiple spaces, which is why I changed the split method to use regex instead of a fixed "   " (three spaces) string.
```

I tried its patch and it works

**Comment by hkup859** [comment]
I didn't realize it had to use specific types, I just thought it needed to be valid JS. The code itself runs fine and outputs the correct result independent of this benchmark program. I'm not sure why the benchmarking project has issues with it. I'll add some of it's tweaks and submit it.

**Comment by sigmaSd** [comment]
No it only accepts javascript the types won't work, but the issue with the code is manipulating string instead of parsing them to numbers

**Comment by hkup859** [comment]
Found the real issue, it isn't related to converting strings to numbers or anything, it's just that the day1.txt file has empty space at the end. Explicity conversion wasn't necessary and in the Claude example can be removed without impact. The only part needed is either removing the extra line in the day1.txt or adding that isNaN check to the math.abs section.

**Comment by sigmaSd** [comment]
cool lets see how you score then

**Comment by hkup859** [comment]
Thanks for your fast responses btw, really cool project and was glad I could finally test my solution!

Without the regex it got 2ms.

**Comment by sigmaSd** [comment]
Awesome thanks for trying it out

**Comment by hkup859** [comment]
Also added a PR in case you wanted to remove that extra blank line in the day1.txt

https://github.com/sigmaSd/Aoc2024Bench/pull/2
